# Enable multipart uploads
spring.servlet.multipart.enabled=true

# MULTIPART FILE SIZE
spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=8000MB
spring.servlet.multipart.max-request-size=8000MB

# Set Storage Location
# spring.servlet.multipart.location=${SERVLET_LOCATION}

# File Storage Folder: based on Root project
work.drive=upload-download-api/work-drive