# Enable multipart uploads
spring.servlet.multipart.enabled=true

# MULTIPART FILE SIZE
spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=8000MB
spring.servlet.multipart.max-request-size=8000MB

# File Storage Properties
work.drive=upload-download/work-drive